export const REGISTER_REQUEST ='REGISTER_REQUEST';
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_ERROR="REGISTER_ERROR";

export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_ERROR="LOGIN_ERROR";

export const RELOGIN_REQUEST="RELOGIN_REQUEST";
export const RELOGIN_SUCCESS="RELOGIN_SUCCESS";
export const RELOGIN_ERROR="RELOGIN_ERROR";

export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_ERROR="LOGOUT_ERROR";

export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_ERROR="GET_USER_ERROR"
export const GET_USER_REQUEST="GET_USER_REQUEST"

export const EDIT_USER_SUCCESS="EDIT_USER_SUCCESS"
export const EDIT_USER_ERROR="EDIT_USER_ERROR"
export const EDIT_USER_REQUEST="EDIT_USER_REQUEST"